name: Build and release

on:
  push:
    tags:
      - "v*.*.*"

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write

jobs:
  build-macos:
    name: Build MacOS Artifact
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: build macos artifact
        run: cargo build --release

      - name: Rename file
        run: mv target/release/nais-env target/release/nais-env-macos

      - name: upload macos artifact
        uses: actions/upload-artifact@v4
        with:
          name: nais-env-macosx
          path: target/release/nais-env-macos

  build-linux:
    name: Build Linux Artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: build macos artifact
        run: cargo build --release

      - name: Rename file
        run: mv target/release/nais-env target/release/nais-env-linux

      - name: upload linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: nais-env-linux
          path: target/release/nais-env-linux

  build-windows:
    name: Build Windows Artifact
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: build windows artifact
        run: cargo build --release

      - name: List files
        run: dir /target/release

      - name: Rename file
        run: mv target/release/nais-env target/release/nais-env.exe

      - name: upload windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: nais-env.exe
          path: /target/release/nais-env.exe

  release-to-github:
    name: Release
    runs-on: ubuntu-latest
    needs: [build-macos, build-linux]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: nais-env-macosx
          path: release-macosx

      - uses: actions/download-artifact@v4
        with:
          name: nais-env-linux
          path: release-linux

      - uses: actions/download-artifact@v4
        with:
          name: nais-env-windows
          path: target/release/nais-env-windows
      - uses: ncipollo/release-action@v1
        name: Release
        with:
          artifacts: "release-linux/nais-env-linux,release-macosx/nais-env-macos"
          replacesArtifacts: true
          generateReleaseNotes: true
          artifactErrorsFailBuild: true
