# Hentet fra https://fpira.com/blog/2025/01/cross-compilation-in-rust

name: Rust

on:
  push:
    branches: ["main", "4-github-actions"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: build macos artifact
        run: cargo build --release

      - name: upload macos artifact
        uses: actions/upload-artifact@v4
        with:
          name: nais-env-macosx
          path: target/release/nais-env
