# Hentet fra https://fpira.com/blog/2025/01/cross-compilation-in-rust

name: Build and release

on:
  push:
    tags:
      - "v*.*.*"

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: build macos artifact
        run: cargo build --release

      - name: upload macos artifact
        uses: actions/upload-artifact@v4
        with:
          name: nais-env-macosx
          path: target/release/nais-env

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: build macos artifact
        run: cargo build --release

      - name: upload linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: nais-env-linux
          path: target/release/nais-env

  #  build-windows:
  #    runs-on: windows-latest
  #    steps:
  #      - uses: actions/checkout@v1
  #      - uses: actions-rust-lang/setup-rust-toolchain@v1
  #      - name: build macos artifact
  #        run: cargo build --release
  #
  #      - name: upload windows artifact
  #        uses: actions/upload-artifact@v4
  #        with:
  #          name: nais-env-windows
  #          path: target/release/nais-env

  release-to-github:
    runs-on: ubuntu-latest
    needs: [build-macos, build-linux]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: nais-env-macosx
          path: release/mac/nais-env

      - uses: actions/download-artifact@v4
        with:
          name: nais-env-linux
          path: release/linux/nais-env

      #      - uses: actions/download-artifact@v4
      #        with:
      #          name: nais-env-windows
      #          path: target/release/nais-env-windows
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: nais-env-${{ github.ref_name }}
          files: |
            release/linux/nais-env
            release/mac/nais-env
          generate_release_notes: true
